apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: devdb-password-externalsecret
  namespace: aws-database-ns # target namespace
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: aws-secretstore
    kind: SecretStore
  target:
    name: proddb-password # name of secret
  data:
  - secretKey: password # 'key' of secret
    remoteRef:
      key: proddb # secret name
      version: "AWSCURRENT"