apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: devdb-password-externalsecret
  namespace: database-ns # target namespace
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secretstore
    kind: SecretStore
  target:
    name: devdb-password # name of secret
  data:
  - secretKey: password  # 'key' of secret in vault
    remoteRef:
      key: devdb
      property: password